apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gov-gr-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gov-gr-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gov-gr-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gov-gr-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gov-gr-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "GOV_GR_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.exporter.apiKeySecretName }}"
                  key: apiKey
            - name: "GOV_GR_COLLECTORS_ENABLE"
              value: "{{ .Values.exporter.collectorsEnable }}"
          ports:
            - name: http
              containerPort: 13211
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /amiok
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /amiok
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
