{{- if .Values.exporter.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gov-gr-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
#   labels:
# {{- if .Values.prometheus.operator.serviceMonitor.selector }}
# {{ toYaml .Values.prometheus.operator.serviceMonitor.selector | indent 4 }}
# {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "gov-gr-exporter.name" . }}
      release: {{ .Release.Name }}
  endpoints:
  - interval: {{ .Values.exporter.serviceMonitor.scrapeInterval }}
  {{- if .Values.exporter.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.exporter.serviceMonitor.scrapeTimeout }}
  {{- end }}
#   {{- if .Values.rabbitmqPrometheusPlugin.enabled }}
#     port: metrics
#     path: {{ .Values.rabbitmqPrometheusPlugin.path }}
#   {{- else }}
#     port: exporter
#   {{- end }}
  namespaceSelector:
    any: true
{{- end }}